
const $=s=>document.querySelector(s);const $all=s=>Array.from(document.querySelectorAll(s));
let currentCity=localStorage.getItem('city')||'praha';$('#citySelect').value=currentCity;
$all('.top-tabs .tab').forEach(btn=>{btn.addEventListener('click',()=>{const tab=btn.dataset.tab;if(!tab){if(btn.id==='toggleMenu'){document.querySelector('.top-tabs').classList.toggle('hide-menu');btn.textContent=document.querySelector('.top-tabs').classList.contains('hide-menu')?'🙉 Показати меню':'🙈 Сховати меню';}return;}
$all('.top-tabs .tab').forEach(b=>b.classList.toggle('active',b===btn));$all('.view').forEach(v=>v.classList.toggle('active',v.id==='view-'+tab));});});
$('#participantsBtn').addEventListener('click',()=>$('#participantsPanel').hidden=false);$('#participantsClose').addEventListener('click',()=>$('#participantsPanel').hidden=true);
$('#profileBtn').addEventListener('click',()=>$('#profileModal').hidden=false);$('#profileClose').addEventListener('click',()=>$('#profileModal').hidden=true);
$('#citySelect').addEventListener('change',e=>{currentCity=e.target.value;localStorage.setItem('city',currentCity);attachChatFeed();attachRentFeed();loadCityWall();loadMap();});
let usersCache={};const usersPublicRef=db.ref('usersPublic');usersPublicRef.on('value',snap=>{usersCache=snap.val()||{};renderParticipants();renderAllVisible();});
function renderAllVisible(){attachChatFeed();attachRentFeed();}
function presenceInit(user){const ref=db.ref('presence/'+user.uid);ref.set({state:'online',ts:firebase.database.ServerValue.TIMESTAMP});ref.onDisconnect().set({state:'offline',ts:firebase.database.ServerValue.TIMESTAMP});
db.ref('presence').on('value',s=>{const all=s.val()||{};const online=Object.values(all).filter(x=>x&&x.state==='online').length;$('#onlineCounter').textContent='Онлайн (прибл.): '+online;});}
auth.onAuthStateChanged(async user=>{if(user){presenceInit(user);const uref=db.ref('usersPublic/'+user.uid);const sn=await uref.get();if(!sn.exists()){await uref.set({displayName:user.displayName||'Користувач',photoURL:window.DEFAULT_AVATAR,role:'seeker',plan:'free'});}loadMyProfile();loadCityWall();attachChatFeed();attachRentFeed();loadMap();setupAdminUI(user);}else{attachChatFeed();attachRentFeed();loadMap();}});
async function loadMyProfile(){const u=auth.currentUser;if(!u)return;const p=(await db.ref('usersPublic/'+u.uid).get()).val()||{};$('#myAvatar').src=p.photoURL||window.DEFAULT_AVATAR;$('#myName').textContent=p.displayName||'Користувач';$('#myRole').textContent=p.role||'seeker';$('#myPlan').textContent=p.plan||'free';$('#nickInput').value=p.displayName||'';$('#avatarInput').value=p.photoURL||'';$('#roleInput').value=p.role||'seeker';}
$('#saveProfile').addEventListener('click',async()=>{const u=auth.currentUser;if(!u)return;const displayName=$('#nickInput').value.trim()||'Користувач';const photoURL=$('#avatarInput').value.trim()||window.DEFAULT_AVATAR;const role=$('#roleInput').value;await db.ref('usersPublic/'+u.uid).update({displayName,photoURL,role});$('#myAvatar').src=photoURL;$('#myName').textContent=displayName;$('#myRole').textContent=role;alert('Профіль збережено');});
function renderParticipants(){const list=$('#participantsList');list.innerHTML='';Object.entries(usersCache).forEach(([uid,u])=>{const div=document.createElement('div');div.className='msg';div.innerHTML=`<span class="avatar"><img src="${u.photoURL||window.DEFAULT_AVATAR}" alt=""></span><div class="bubble"><div class="name">${u.displayName||'Користувач'}</div><div class="text"><button data-dm="${uid}">Написати</button> <button data-addfriend="${uid}">Додати у друзі</button></div></div>`;list.appendChild(div);});list.querySelectorAll('[data-dm]').forEach(b=>b.onclick=()=>openDM(b.dataset.dm));}
let chatFeedOff=null;function attachChatFeed(){if(chatFeedOff){chatFeedOff();chatFeedOff=null;}const ref=db.ref('messages/'+currentCity).limitToLast(100);ref.off();ref.on('value',snap=>{const feed=$('#chatFeed');feed.innerHTML='';const val=snap.val()||{};Object.entries(val).sort((a,b)=>a[1].ts-b[1].ts).forEach(([id,msg])=>{const u=usersCache[msg.by]||{};const name=u.displayName||'Користувач';const ava=u.photoURL||window.DEFAULT_AVATAR;const div=document.createElement('div');div.className='msg';const textHtml=msg.photo?`<img src="${msg.photo}" alt="">`+(msg.text?('<div class="text">'+escapeHtml(msg.text)+'</div>'):''):('<div class="text">'+escapeHtml(msg.text||'')+'</div>');div.innerHTML=`<span class="avatar"><img src="${ava}" alt=""></span><div class="bubble"><div class="name">${name}</div>${textHtml}</div>`;div.querySelector('.avatar').addEventListener('click',()=>openProfileOf(msg.by));feed.appendChild(div);});feed.scrollTop=feed.scrollHeight;});chatFeedOff=()=>ref.off();}
function escapeHtml(s){return (s||'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));}
async function sendChatMessage(text,photo){const u=auth.currentUser;const by=u?u.uid:'guest';const payload={by,text:text||null,photo:photo||null,ts:Date.now()};await db.ref('messages/'+currentCity).push(payload);}
$('#chatSend').addEventListener('click',async()=>{const text=$('#chatInput').value.trim();let photo=null;if(/^https?:\/\//.test(text)&&(/(\.jpg|\.jpeg|\.png|\.webp|\?)/i.test(text))){photo=text;}
if($('#chatFile').files[0]){photo=await fileToUrl($('#chatFile').files[0]);$('#chatFile').value='';}await sendChatMessage(photo?null:text,photo);$('#chatInput').value='';});
async function fileToUrl(file){if(!file)return null;if(window.USE_STORAGE&&window.storage){const path='chat_images/'+(auth.currentUser?auth.currentUser.uid:'guest')+'/'+Date.now()+'_'+file.name;const ref=storage.ref().child(path);await ref.put(file);return await ref.getDownloadURL();}else{return await new Promise(res=>{const r=new FileReader();r.onload=()=>res(r.result);r.readAsDataURL(file);});}}
function attachRentFeed(){const ref=db.ref('rentMessages/'+currentCity).limitToLast(100);ref.off();ref.on('value',snap=>{const feed=$('#rentFeed');feed.innerHTML='';const val=snap.val()||{};Object.entries(val).sort((a,b)=>a[1].ts-b[1].ts).forEach(([id,msg])=>{const u=usersCache[msg.by]||{};const name=u.displayName||'Користувач';const ava=u.photoURL||window.DEFAULT_AVATAR;const div=document.createElement('div');div.className='msg';const textHtml=msg.photo?`<img src="${msg.photo}" alt="">`+(msg.text?('<div class="text">'+escapeHtml(msg.text)+'</div>'):''):('<div class="text">'+escapeHtml(msg.text||'')+'</div>');div.innerHTML=`<span class="avatar"><img src="${ava}" alt=""></span><div class="bubble"><div class="name">${name}</div>${textHtml}</div>`;$('#rentFeed').appendChild(div);});$('#rentFeed').scrollTop=$('#rentFeed').scrollHeight;});}
$('#rentSend').addEventListener('click',async()=>{const u=auth.currentUser;const by=u?u.uid:'guest';let text=$('#rentInput').value.trim()||null;let photo=null;if($('#rentFile').files[0])photo=await fileToUrl($('#rentFile').files[0]);await db.ref('rentMessages/'+currentCity).push({by,text,photo,ts:Date.now()});$('#rentInput').value='';$('#rentFile').value='';});
let currentDM=null;function openDM(otherUid){const me=auth.currentUser;if(!me){alert('Спочатку увійдіть');return;}currentDM=[me.uid,otherUid].sort().join('_');$all('.top-tabs .tab').forEach(b=>{if(b.dataset.tab==='dm')b.click();});const ref=db.ref('privateMessages/'+currentDM).limitToLast(200);ref.off();ref.on('value',snap=>{const feed=$('#dmMessages');feed.innerHTML='';const val=snap.val()||{};Object.entries(val).sort((a,b)=>a[1].ts-b[1].ts).forEach(([id,msg])=>{const u=usersCache[msg.by]||{};const name=u.displayName||'Користувач';const ava=u.photoURL||window.DEFAULT_AVATAR;const div=document.createElement('div');div.className='msg';const textHtml=msg.photo?`<img src="${msg.photo}" alt="">`+(msg.text?('<div class="text">'+escapeHtml(msg.text)+'</div>'):''):('<div class="text">'+escapeHtml(msg.text||'')+'</div>');div.innerHTML=`<span class="avatar"><img src="${ava}" alt=""></span><div class="bubble"><div class="name">${name}</div>${textHtml}</div>`;feed.appendChild(div);});feed.scrollTop=feed.scrollHeight;});}
$('#dmSend').addEventListener('click',async()=>{if(!currentDM)return;const me=auth.currentUser;if(!me)return;const text=$('#dmInput').value.trim()||null;let photo=null;if($('#dmFile').files[0])photo=await fileToUrl($('#dmFile').files[0]);await db.ref('privateMessages/'+currentDM).push({by:me.uid,text,photo,ts:Date.now()});$('#dmInput').value='';$('#dmFile').value='';});
function openProfileOf(uid){const u=usersCache[uid];if(!u)return;const el=document.createElement('div');el.className='modal';el.innerHTML=`<div class="card"><header><b>Профіль: ${u.displayName||'Користувач'}</b><button class="x">✖</button></header><div class="row"><div class="avatar"><img src="${u.photoURL||window.DEFAULT_AVATAR}"></div><div>План: ${u.plan||'free'} · Роль: ${u.role||'seeker'}</div></div><div class="row"><button data-dm="${uid}">Написати</button> <button data-add="${uid}">Додати у друзі</button></div></div>`;document.body.appendChild(el);el.querySelector('.x').onclick=()=>el.remove();el.querySelector('[data-dm]').onclick=()=>{openDM(uid);el.remove();};}
function setupAdminUI(user){const isAdmin=user&&user.email===window.ADMIN_EMAIL;$('#adminOnly').style.display=isAdmin?'':'none';$('#helpAdminBox').style.display=isAdmin?'':'none';$('#adsAdmin').style.display=isAdmin?'':'none';$('#mapAdmin').style.display=isAdmin?'':'none';
if(isAdmin){$('#botStart').onclick=()=>{const city=$('#botCity').value;const interval=$('#botInterval').value;const text=$('#botText').value;const photo=$('#botPhoto').value||null;startBot({city,interval,text,photo});$('#botsStatus').textContent='Бот запущено для '+city;};$('#botStop').onclick=()=>{stopBot($('#botCity').value);$('#botsStatus').textContent='Зупинено';};$('#saveCityWall').onclick=async()=>{const url=$('#cityWallUrl').value.trim();await db.ref('settings/walls/'+currentCity).set(url);applyWall(url);alert('Фон міста оновлено');};$('#poiAdd').onclick=async()=>{if(!window._map)return;const c=window._map.getCenter();const item={title:$('#poiTitle').value||'Місце',type:$('#poiType').value||'help',lat:c.lat,lng:c.lng};await db.ref('map/poi/'+currentCity).push(item);alert('Точку додано');};}}
async function loadCityWall(){const sn=await db.ref('settings/walls/'+currentCity).get();const url=sn.val();applyWall(url);}function applyWall(url){if(url)document.body.style.setProperty('--wall',`url("${url}")`);}
$('#helpPost').addEventListener('click',async()=>{const title=$('#helpTitle').value.trim();const link=$('#helpLink').value.trim();const photo=$('#helpImageUrl').value.trim()||null;await db.ref('help/'+currentCity+'/cards').push({title,link,photo,ts:Date.now()});$('#helpTitle').value='';$('#helpLink').value='';$('#helpImageUrl').value='';});
db.ref('help/'+currentCity+'/cards').on('value',snap=>{const g=$('#helpGrid');g.innerHTML='';const v=snap.val()||{};Object.values(v).sort((a,b)=>b.ts-a.ts).forEach(it=>{const d=document.createElement('div');d.className='card';d.innerHTML=(it.photo?`<img src="${it.photo}" style="width:100%;border-radius:8px">`:'')+`<div><b>${escapeHtml(it.title||'')}</b></div>`+(it.link?`<div><a href="${it.link}" target="_blank">перейти</a></div>`:'');g.appendChild(d);});});
$('#adPublish').addEventListener('click',async()=>{const t=$('#adTitle').value.trim();const p=$('#adPhoto').value.trim()||null;const x=$('#adText').value.trim()||null;await db.ref('ads/'+currentCity).push({title:t,photo:p,text:x,ts:Date.now()});$('#adTitle').value='';$('#adPhoto').value='';$('#adText').value='';alert('Опубліковано');});
db.ref('ads/'+currentCity).on('value',snap=>{const g=$('#adsGrid');g.innerHTML='';const v=snap.val()||{};Object.values(v).sort((a,b)=>b.ts-a.ts).forEach(it=>{const d=document.createElement('div');d.className='card';d.innerHTML=(it.photo?`<img src="${it.photo}" style="width:100%;border-radius:8px">`:'')+`<div><b>${escapeHtml(it.title||'')}</b></div>`+(it.text?`<div class="muted">${escapeHtml(it.text)}</div>`:'');g.appendChild(d);});});
let markers=[];function loadMap(){if(!window.L)return;if(!window._map){window._map=L.map('map').setView([50.087,14.421],11);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'&copy; OpenStreetMap'}).addTo(window._map);}markers.forEach(m=>window._map.removeLayer(m));markers=[];db.ref('map/poi/'+currentCity).off();db.ref('map/poi/'+currentCity).on('value',snap=>{markers.forEach(m=>window._map.removeLayer(m));markers=[];const v=snap.val()||{};Object.values(v).forEach(p=>{const m=L.marker([p.lat,p.lng]).addTo(window._map).bindPopup(`<b>${escapeHtml(p.title||'')}</b><br>${escapeHtml(p.type||'')}`);markers.push(m);});});}
document.addEventListener('DOMContentLoaded',()=>{attachChatFeed();attachRentFeed();loadMap();});
