/* Core app (shortened for zip tool) */
const DB={messages:'messages',rentMessages:'rentMessages',privateMessages:'privateMessages',inboxMeta:'inboxMeta',friends:'friends',friendRequests:'friendRequests',users:'users',usersPublic:'usersPublic',help:'help',map:'map',settings:'settings',payments:'payments',bots:'bots',botsMeta:'botsMeta',banned:'banned',ann:'announcements'};
try{ if(!firebase.apps.length){ firebase.initializeApp(window.FIREBASE_CONFIG);} }catch(e){}
const auth=firebase.auth(); const db=firebase.database();
const $=(q,r=document)=>r.querySelector(q); const $$=(q,r=document)=>Array.from(r.querySelectorAll(q));
const esc=s=>(s+'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;','\'':'&#39;'}[c]));
let CURRENT_CITY=localStorage.getItem('city')||'praha'; let usersCache={}; let me=null; let pendingChatPhoto=null,pendingRentPhoto=null,pendingDmPhoto=null;
function now(){return Date.now();} function threadId(a,b){return [a,b].sort().join('_');}
document.addEventListener('DOMContentLoaded',()=>{
  $('#citySelect').value=CURRENT_CITY; $('#citySelect').addEventListener('change',()=>{CURRENT_CITY=$('#citySelect').value;localStorage.setItem('city',CURRENT_CITY);subChat();subRent();subHelp();subMap();updateWall();});
  $('#tabs').addEventListener('click',e=>{const b=e.target.closest('.tab');if(!b)return; $$('.tab').forEach(x=>x.classList.remove('active')); b.classList.add('active'); $$('.view').forEach(v=>v.classList.remove('active')); $('#view-'+b.dataset.tab).classList.add('active');});
  $('#participantsBtn').addEventListener('click',()=>$('#participantsPanel').hidden=false); $('#participantsClose').addEventListener('click',()=>$('#participantsPanel').hidden=true);
  $('#bellBtn').addEventListener('click',()=>$('#notifPanel').hidden=false); $('#notifClose').addEventListener('click',()=>$('#notifPanel').hidden=true); $('#notifClear').addEventListener('click',()=>$('#notifList').innerHTML='');
  $('#chatSend').addEventListener('click',sendChat); $('#chatFile').addEventListener('change',e=>toData(e.target.files[0],u=>{pendingChatPhoto=u;$('#chatToast').hidden=false;}));
  $('#rentSend').addEventListener('click',sendRent); $('#rentFile').addEventListener('change',e=>toData(e.target.files[0],u=>{pendingRentPhoto=u;$('#rentToast').hidden=false;}));
  $('#dmSend').addEventListener('click',sendDm); $('#dmFile').addEventListener('change',e=>toData(e.target.files[0],u=>{pendingDmPhoto=u;}));
  $('#btnPayments').addEventListener('click',()=>{$('#paymentsModal').hidden=false;if(me&&me.email===window.ADMIN_EMAIL)$('#payAdmin').hidden=false;}); $('#paymentsClose').addEventListener('click',()=>$('#paymentsModal').hidden=true);
  $('#paySend').addEventListener('click',paySend); $('#payRefresh').addEventListener('click',loadPayInbox);
  $('#profileBtn').addEventListener('click',()=>$('#profileModal').hidden=false); $('#profileClose').addEventListener('click',()=>$('#profileModal').hidden=true); $('#profileSave').addEventListener('click',saveProfile);
  $('#helpPost').addEventListener('click',helpPost); $('#annPost').addEventListener('click',annPost);
  $('#adminFillUsersPublic').addEventListener('click',adminFillUsersPublic); $('#adminAddMeFriends').addEventListener('click',adminAddMeFriends); $('#adminOpenPayInbox').addEventListener('click',()=>{$('#paymentsModal').hidden=false;$('#payAdmin').hidden=false;loadPayInbox();});
  $('#botSave').addEventListener('click',botSave); $('#botStart').addEventListener('click',()=>botEnable(true)); $('#botStop').addEventListener('click',()=>botEnable(false));
  initMap(); $('#poiAdd').addEventListener('click',addPoi); $('#saveCityWall').addEventListener('click',()=>setCityWall(false)); $('#saveGlobalWall').addEventListener('click',()=>setCityWall(true));
});
function toData(f,cb){ if(!f)return; const r=new FileReader(); r.onload=()=>cb(r.result); r.readAsDataURL(f); }
function renderMsg(cont,m){const w=document.createElement('div');w.className='msg';const a=document.createElement('div');a.className='ava';const im=document.createElement('img');im.src=(usersCache[m.by]?.avatar)||'https://i.pravatar.cc/64';a.appendChild(im);const b=document.createElement('div');b.className='b';const n=document.createElement('div');n.className='name';n.textContent=(usersCache[m.by]?.name)||m.by.slice(0,6);const t=document.createElement('div');t.className='text';const s=document.createElement('span');s.textContent=m.text||'';t.appendChild(s); if(m.photo){const pi=new Image();pi.src=m.photo;pi.style.display='block';pi.style.marginTop='6px';t.appendChild(pi);} b.appendChild(n); b.appendChild(t); w.appendChild(a); w.appendChild(b); cont.appendChild(w); cont.scrollTop=cont.scrollHeight; }
auth.onAuthStateChanged(async u=>{me=u; if(u){ setInterval(()=>db.ref('presence/'+u.uid).set(now()),60000); const upRef=db.ref(DB.usersPublic+'/'+u.uid); if(!(await upRef.get()).exists()) await upRef.set({name:u.displayName||'Користувач',avatar:u.photoURL||'https://i.pravatar.cc/64'}); const prof=(await db.ref(DB.users+'/'+u.uid).get()).val()||{}; $('#myEmail').textContent=u.email||''; $('#myRole').textContent=prof.role||'seeker'; $('#myPlan').textContent=prof.plan||'free'; const up=(await upRef.get()).val()||{}; $('#myName').textContent=up.name||'Користувач'; $('#myAvatar').src=up.avatar||'https://i.pravatar.cc/64'; const isAdmin=u.email===window.ADMIN_EMAIL; $('#adminTools').hidden=!isAdmin; $('#helpAdminBox').hidden=!isAdmin; $('#annAdminBox').hidden=!isAdmin; $('#mapAdmin').hidden=!isAdmin?true:false; if((prof.plan||'free')!=='free'||isAdmin) $('#premiumBots').hidden=false; else $('#premiumBots').hidden=true; subUsers(); subChat(); subRent(); subDmSidebar(); subFriends(); subHelp(); subMap(); subAnn(); updateWall(); }});
function subUsers(){ db.ref(DB.usersPublic).on('value',s=>{usersCache=s.val()||{}; renderParticipants();}); }
async function renderParticipants(){ const box=$('#participantsList'); box.innerHTML=''; const pres=(await db.ref('presence').get()).val()||{}; const banned=(await db.ref(DB.banned).get()).val()||{}; const isAdmin=me&&me.email===window.ADMIN_EMAIL; let on=0; for(const uid in usersCache){ const u=usersCache[uid]; const online=(now()-(pres[uid]||0))<180000; if(online)on++; const d=document.createElement('div'); d.className='msg'; d.innerHTML=`<div class="ava"><img src="${u.avatar||'https://i.pravatar.cc/64'}"></div><div class="b"><div class="name">${esc(u.name||uid.slice(0,6))} ${online?'<span class="muted">• online</span>':''} ${banned[uid]?'[banned]':''}</div><div class="text">${uid}</div>${isAdmin?'<div class="row"><button data-ban="'+uid+'">'+(banned[uid]?'Розбанити':'Забанити')+'</button></div>':''}</div>`; box.appendChild(d); if(isAdmin){ d.querySelector('[data-ban]')?.addEventListener('click',async()=>{ if(banned[uid]) await db.ref(DB.banned+'/'+uid).remove(); else await db.ref(DB.banned+'/'+uid).set(true); renderParticipants();}); } } const count=(me&&me.email===window.ADMIN_EMAIL)?on:on*12; $('#onlineCounter').textContent='Онлайн (прибл.): '+count; }
function subChat(){ const f=$('#chatFeed'); f.innerHTML=''; db.ref(DB.messages+'/'+CURRENT_CITY).limitToLast(200).on('child_added',s=>renderMsg(f,s.val())); }
async function sendChat(){ if(!(me&&me.uid)) return alert('Увійдіть'); const text=$('#chatInput').value.trim(); if(!text && !pendingChatPhoto) return; const m={by:me.uid,ts:now()}; if(text) m.text=text; if(pendingChatPhoto) m.photo=pendingChatPhoto; await db.ref(DB.messages+'/'+CURRENT_CITY).push(m); $('#chatInput').value=''; pendingChatPhoto=null; $('#chatToast').hidden=true; }
function subRent(){ const f=$('#rentFeed'); f.innerHTML=''; db.ref(DB.rentMessages+'/'+CURRENT_CITY).limitToLast(200).on('child_added',s=>renderMsg(f,s.val())); }
async function sendRent(){ if(!(me&&me.uid)) return alert('Увійдіть'); const text=$('#rentInput').value.trim(); if(!text && !pendingRentPhoto) return; const m={by:me.uid,ts:now()}; if(text)m.text=text; if(pendingRentPhoto)m.photo=pendingRentPhoto; await db.ref(DB.rentMessages+'/'+CURRENT_CITY).push(m); $('#rentInput').value=''; pendingRentPhoto=null; $('#rentToast').hidden=true; }
let dmRef=null,currentDmUid=null; function subDmSidebar(){ if(!me) return; const sbar=$('#dmSidebar'); sbar.innerHTML=''; db.ref(DB.inboxMeta+'/'+me.uid).on('child_added',snap=>{ const uid=snap.key; const el=document.createElement('div'); el.className='msg'; el.innerHTML=`<div class="ava"><img src="${(usersCache[uid]?.avatar)||'https://i.pravatar.cc/32'}"></div><div class="b"><div class="name">${(usersCache[uid]?.name)||uid.slice(0,6)}</div></div>`; el.onclick=()=>openDmWith(uid); sbar.appendChild(el); }); }
function openDmWith(uid){ currentDmUid=uid; $('#dmMessages').innerHTML=''; $('#dmHeader').textContent=(usersCache[uid]?.name)||uid.slice(0,6); const tid=threadId(me.uid,uid); if(dmRef){ try{ db.ref(DB.privateMessages+'/'+tid).off(); }catch{} } dmRef=db.ref(DB.privateMessages+'/'+tid).limitToLast(200); dmRef.on('child_added',s=>renderMsg($('#dmMessages'),s.val())); }
async function sendDm(){ if(!me||!currentDmUid) return; const text=$('#dmInput').value.trim(); if(!text && !pendingDmPhoto) return; const tid=threadId(me.uid,currentDmUid); const m={by:me.uid,ts:now()}; if(text)m.text=text; if(pendingDmPhoto)m.photo=pendingDmPhoto; await db.ref(DB.privateMessages+'/'+tid).push(m); await db.ref(DB.inboxMeta+'/'+me.uid+'/'+currentDmUid).set({ts:now()}); await db.ref(DB.inboxMeta+'/'+currentDmUid+'/'+me.uid).set({ts:now()}); $('#dmInput').value=''; pendingDmPhoto=null; }
function subFriends(){ if(!me) return; $('#friendRequests').innerHTML=''; db.ref(DB.friendRequests+'/'+me.uid).on('child_added',s=>{ const from=s.key; const d=document.createElement('div'); d.className='msg'; d.innerHTML=`<div class="ava"><img src="${(usersCache[from]?.avatar)||'https://i.pravatar.cc/32'}"></div><div class="b"><div class="name">${(usersCache[from]?.name)||from.slice(0,6)}</div><div class="row"><button data-acc="${from}">Прийняти</button></div></div>`; d.querySelector('[data-acc]').onclick=()=>acceptFriend(from); $('#friendRequests').appendChild(d); }); $('#friendsList').innerHTML=''; db.ref(DB.friends+'/'+me.uid).on('child_added',s=>{ const uid=s.key; const el=document.createElement('div'); el.className='msg'; el.innerHTML=`<div class="ava"><img src="${(usersCache[uid]?.avatar)||'https://i.pravatar.cc/32'}"></div><div class="b"><div class="name">${(usersCache[uid]?.name)||uid.slice(0,6)}</div></div>`; el.onclick=()=>openDmWith(uid); $('#friendsList').appendChild(el); }); }
async function acceptFriend(from){ const my=me.uid; await db.ref(DB.friends+'/'+my+'/'+from).set({status:'accepted',ts:now()}); await db.ref(DB.friends+'/'+from+'/'+my).set({status:'accepted',ts:now()}); await db.ref(DB.friendRequests+'/'+my+'/'+from).remove(); }
function subHelp(){ const g=$('#helpGrid'); g.innerHTML=''; db.ref(DB.help+'/'+CURRENT_CITY+'/cards').limitToLast(200).on('child_added',s=>{ const v=s.val()||{}; const card=document.createElement('div'); card.className='card'; if(v.image){const im=new Image(); im.src=v.image; card.appendChild(im);} const t=document.createElement('div'); t.innerHTML=`<b>${(v.title||'Без назви')}</b>`; card.appendChild(t); if(v.text){const p=document.createElement('div'); p.textContent=v.text; card.appendChild(p);} if(v.link){const a=document.createElement('a'); a.href=v.link; a.target='_blank'; a.textContent='Відкрити →'; card.appendChild(a);} g.prepend(card); }); }
async function helpPost(){ if(!me||me.email!==window.ADMIN_EMAIL) return; const title=$('#helpTitle').value.trim(); const text=$('#helpText').value.trim(); const link=$('#helpLink').value.trim(); const image=$('#helpImageUrl').value.trim(); if(!title&&!text&&!image)return; await db.ref(DB.help+'/'+CURRENT_CITY+'/cards').push({title,text,link:link||null,image:image||null,ts:now(),by:me.uid}); $('#helpTitle').value=''; $('#helpText').value=''; $('#helpLink').value=''; $('#helpImageUrl').value=''; }
function subAnn(){ const g=$('#annFeed'); g.innerHTML=''; db.ref(DB.ann+'/'+CURRENT_CITY).limitToLast(200).on('child_added',s=>{ const v=s.val()||{}; const card=document.createElement('div'); card.className='card'; if(v.image){const im=new Image(); im.src=v.image; card.appendChild(im);} const t=document.createElement('div'); t.innerHTML=`<b>${v.title||'Без назви'}</b> ${v.price?(' · '+v.price):''}`; card.appendChild(t); if(v.kind){const k=document.createElement('div'); k.className='muted'; k.textContent=v.kind; card.appendChild(k);} if(v.text){const p=document.createElement('div'); p.textContent=v.text; card.appendChild(p);} g.prepend(card); }); }
async function annPost(){ if(!me||me.email!==window.ADMIN_EMAIL) return; const title=$('#annTitle').value.trim(); const text=$('#annText').value.trim(); const price=$('#annPrice').value.trim(); const image=$('#annImageUrl').value.trim(); const kind=$('#annKind').value; await db.ref(DB.ann+'/'+CURRENT_CITY).push({title,text,price:price||null,image:image||null,kind,ts:now(),by:me.uid}); $('#annTitle').value=''; $('#annText').value=''; $('#annPrice').value=''; $('#annImageUrl').value=''; }
async function paySend(){ if(!me)return alert('Увійдіть'); const plan=$('#payPlan').value; const amount=$('#payAmount').value.trim()||null; let receipt=null; const f=$('#payFile').files[0]; if(f){ const r=new FileReader(); r.onload=async()=>{ receipt=r.result; await db.ref(DB.payments+'/requests/'+me.uid).push({uid:me.uid,plan,amount,receipt,ts:now()}); alert('Заявку на оплату надіслано'); }; r.readAsDataURL(f);} else { await db.ref(DB.payments+'/requests/'+me.uid).push({uid:me.uid,plan,amount,receipt:null,ts:now()}); alert('Заявку на оплату надіслано'); } }
async function loadPayInbox(){ if(!me||me.email!==window.ADMIN_EMAIL) return; const inbox=$('#payInbox'); inbox.innerHTML=''; const snap=await db.ref(DB.payments+'/requests').get(); const all=snap.val()||{}; for(const uid in all){ for(const key in all[uid]){ const r=all[uid][key]; const row=document.createElement('div'); row.className='msg'; row.innerHTML=`<div class="ava"><img src="${(usersCache[uid]?.avatar)||'https://i.pravatar.cc/32'}"></div><div class="b"><div class="name">${(usersCache[uid]?.name)||uid}</div><div class="text">План: <b>${r.plan}</b> ${r.amount?(' · '+r.amount):''} ${r.receipt?'<a target="_blank" href="'+r.receipt+'">чек</a>':''}</div><div class="row"><button data-approve="${uid}" data-plan="${r.plan}">Підтвердити</button></div></div>`; row.querySelector('[data-approve]').onclick=async()=>{const plan=row.querySelector('[data-approve]').dataset.plan; await db.ref(DB.users+'/'+uid+'/plan').set(plan); alert('План '+plan+' активовано');}; inbox.appendChild(row);} } }
async function saveProfile(){ if(!me)return; const nick=$('#profileNick').value.trim(); const avatar=$('#profileAvatarUrl').value.trim(); if(nick) await db.ref(DB.usersPublic+'/'+me.uid+'/name').set(nick); if(avatar) await db.ref(DB.usersPublic+'/'+me.uid+'/avatar').set(avatar); alert('Збережено'); }
let map,markers=[],poiRef=null; function initMap(){ if(map) return; map=L.map('map').setView([50.0755,14.4378],7); L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap'}).addTo(map); document.addEventListener('keydown',e=>{ if($('#view-map').classList.contains('active')&&me&&me.email===window.ADMIN_EMAIL){ const k=e.key.toLowerCase(); const mp={'v':'vol','s':'shop','p':'pharm','h':'hosp'}; if(mp[k]) $('#poiType').value=mp[k]; } }); }
function subMap(){ markers.forEach(m=>m.remove()); markers=[]; if(poiRef){ try{ poiRef.off(); }catch{} } poiRef=db.ref(DB.map+'/poi/'+CURRENT_CITY); poiRef.on('child_added',s=>{ const v=s.val()||{}; const m=L.marker([v.lat||50.08,v.lng||14.43]).addTo(map); m.bindPopup(`<div style="min-width:180px">${v.img?`<img src="${v.img}" style="width:100%;border-radius:8px;margin-bottom:6px">`:''}<b>${v.title||'Точка'}</b><div>${v.type||''}</div>${v.link?`<div><a target="_blank" href="${v.link}">Відкрити</a></div>`:''}</div>`); markers.push(m); }); }
async function addPoi(){ if(!me||me.email!==window.ADMIN_EMAIL) return; const c=map.getCenter(); const title=$('#poiTitle').value.trim(); const type=$('#poiType').value; const img=$('#poiImageUrl').value.trim(); const link=$('#poiLink').value.trim(); await db.ref(DB.map+'/poi/'+CURRENT_CITY).push({title,type,img:img||null,link:link||null,lat:c.lat,lng:c.lng,ts:now(),by:me.uid}); $('#poiTitle').value=''; $('#poiImageUrl').value=''; $('#poiLink').value=''; }
async function setCityWall(global=false){ if(!me||me.email!==window.ADMIN_EMAIL) return; const url=$('#cityWall').value.trim(); if(!url)return; if(global) await db.ref(DB.settings+'/theme/wallUrl').set(url); else await db.ref(DB.settings+'/theme/cityBackgrounds/'+CURRENT_CITY).set(url); updateWall(); }
async function updateWall(){ try{ const cs=await db.ref(DB.settings+'/theme/cityBackgrounds/'+CURRENT_CITY).get(); const gs=await db.ref(DB.settings+'/theme/wallUrl').get(); const url=(cs.exists()?cs.val():(gs.exists()?gs.val():null))||'https://i.ibb.co/pr18RzG3/charles-bridge-prague.jpg'; document.documentElement.style.setProperty('--wall',`url('${url}')`);}catch(e){} }
async function adminFillUsersPublic(){ if(!me||me.email!==window.ADMIN_EMAIL) return; const us=(await db.ref(DB.users).get()).val()||{}; for(const uid in us){ const up=(await db.ref(DB.usersPublic+'/'+uid).get()).val()||{}; if(!up.name) await db.ref(DB.usersPublic+'/'+uid).set({name:us[uid].name||'Користувач', avatar:'https://i.pravatar.cc/64'});} alert('Готово'); }
async function adminAddMeFriends(){ if(!me||me.email!==window.ADMIN_EMAIL) return; const us=(await db.ref(DB.usersPublic).get()).val()||{}; for(const uid in us){ if(uid===me.uid) continue; await db.ref(DB.friends+'/'+me.uid+'/'+uid).set({status:'accepted',ts:now()}); await db.ref(DB.friends+'/'+uid+'/'+me.uid).set({status:'accepted',ts:now()}); } alert('Додано'); }
async function botSave(){ if(!me)return; const text=$('#botText').value.trim(); const photo=$('#botPhotoUrl').value.trim()||null; const city=$('#botCity').value; const intervalMin=Math.max(15,parseInt($('#botInterval').value||'15',10)); await db.ref(DB.bots+'/'+me.uid).push({city,text,photo,intervalMin,enabled:false,ts:now(),by:me.uid}); alert('Шаблон збережено'); }
async function botEnable(on){ if(!me)return; const q=(await db.ref(DB.bots+'/'+me.uid).limitToLast(1).get()); if(!q.exists()) return alert('Спочатку збережіть шаблон'); const id=Object.keys(q.val()).pop(); await db.ref(DB.bots+'/'+me.uid+'/'+id+'/enabled').set(on); alert(on?'Бот запущено':'Бот зупинено'); }
